server:
    port: 8080
    error:
        include-message: always

spring:
    flyway:
        enabled: true
        baseline-version: 1  # Sửa lỗi: baselineVersion thành baseline-version
        locations: classpath:db/migration
        sql-migration-suffixes: .sql  # Sửa lỗi: sqlMigrationSuffixes thành sql-migration-suffixes
        baseline-on-migrate: true  # Sửa lỗi: baselineOnMigrate thành baseline-on-migrate
        sql-migration-prefix: V  # Sửa lỗi: sqlMigrationPrefix thành sql-migration-prefix
        schemas: public

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update

#    data:
#        jpa:
#            repositories: packages=com.springbootmvcwithentity.demo.dao
#        entity: packages-to-scan=com.springbootmvcwithentity.demo.entity

    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 55MB
            location: ${user.dir}/src/main/resources/static/

#    datasource:
#        jdbcUrl: jdbc:postgresql://tiny.db.elephantsql.com:5432/tgmoniuw  # Sửa url thành jdbcUrl
#        username: tgmoniuw
#        password: BiaAw5KDJHQyNiTE24za4WrxUgL32XZZ
#        driver-class-name: org.postgresql.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/mobileshopdb3  # Sửa url thành jdbcUrl
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.cj.jdbc.Driver


app:
    datasource:
        jdbcUrl: jdbc:postgresql://tiny.db.elephantsql.com:5432/tgmoniuw  # Sửa url thành jdbcUrl
        username: tgmoniuw
        password: BiaAw5KDJHQyNiTE24za4WrxUgL32XZZ
#        jdbcUrl: jdbc:postgresql://localhost:5432/tgmoniuw  # Sửa url thành jdbcUrl
#        username: postgres
#        password: 123456
        driver-class-name: org.postgresql.Driver
#app:
#    datasource:
#        jdbcUrl: jdbc:mysql://localhost:3306/mobileshopdb3  # Sửa url thành jdbcUrl
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.cj.jdbc.Driver
